version: 2.1


# orbs:
  # Declare a dependency on the welcome-orb
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout # checkout source code to working directory
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout # checkout source code to working directory
      - run:
          command: npm run test
  analyze:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout # checkout source code to working directory
      - run:
          command: npm audit
workflows:
  # Name the workflow
  sillians:
    # run the jobs in its own container
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
  